name: Source formatting with clang-format

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Version
      run: clang-format-18 --version

    - name: Run clang-format
      run: |
        clang-format-18 --dry-run -Werror $(git ls-files '*.*pp')

    - name: Report incorrect format
      if: failure()
      run: echo "Some files are not formatted correctly."
