name: Source formatting with clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        clang-format --dry-run -Werror $(git ls-files '*.*pp')

    - name: Report incorrect format
      if: failure()
      run: echo "Some files are not formatted correctly."
