name: Build transferase on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/gcc-cmake-boost
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zlib1g-dev libgtest-dev

      - name: Configure a release build that uses GCC
        run: |
          cmake -B Release \
          -DCMAKE_VERBOSE_MAKEFILE=on \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build a release using GCC
        run: |
          cmake --build Release -j4

      - name: Configure a unit test release build that GCC
        run: |
          cmake -B ReleaseTest \
          -DENABLE_UNIT_TESTS=on \
          -DCMAKE_VERBOSE_MAKEFILE=on \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build a unit test release using GCC
        run: |
          cmake --build ReleaseTest -j4

      - name: Run unit tests
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib
          ctest --test-dir ReleaseTest --output-on-failure
